package atharrison.sandbox.projecteuler;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 *
 *    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 */
public class Problem2 {
    
    public long solve() {
        
        long termA = 1;
        long termB = 2;
        long termC = 0;
        long sum = 0;
        while (termB < 4000000) {
            
            if( termB % 2 == 0) {
                sum += termB;
            }
            
            
            termC = termA + termB;
            termA = termB;
            termB = termC;
        }
        
        
        
        return sum;
    }
}
